version: '3.7'

services:
  # Single Orderer
  orderer1.bpjs-network.com:
    container_name: orderer1.bpjs-network.com
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/bpjs-network.com/orderers/orderer1.bpjs-network.com/msp:/var/hyperledger/orderer/msp
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/genesis.block
    ports:
      - 7050:7050
    networks:
      - bpjs_network
    deploy:
      resources:
        limits:
          memory: 256M

  # BPJS Peer
  peer0.bpjs.bpjs-network.com:
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bpjs-blockchain-fabric_bpjs_network
      - CORE_PEER_ID=peer0.bpjs.bpjs-network.com
      - CORE_PEER_ADDRESS=peer0.bpjs.bpjs-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bpjs.bpjs-network.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bpjs.bpjs-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bpjs.bpjs-network.com:7051
      - CORE_PEER_LOCALMSPID=BPJSMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - FABRIC_LOGGING_SPEC=INFO
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/bpjs.bpjs-network.com/peers/peer0.bpjs.bpjs-network.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051
    networks:
      - bpjs_network
    deploy:
      resources:
        limits:
          memory: 256M

  # Hospital Peer
  peer0.rumahsakit.bpjs-network.com:
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bpjs-blockchain-fabric_bpjs_network
      - CORE_PEER_ID=peer0.rumahsakit.bpjs-network.com
      - CORE_PEER_ADDRESS=peer0.rumahsakit.bpjs-network.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.rumahsakit.bpjs-network.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.rumahsakit.bpjs-network.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.rumahsakit.bpjs-network.com:9051
      - CORE_PEER_LOCALMSPID=RumahSakitMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - FABRIC_LOGGING_SPEC=INFO
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/rumahsakit.bpjs-network.com/peers/peer0.rumahsakit.bpjs-network.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 9051:9051
    networks:
      - bpjs_network
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  bpjs_network:
    driver: bridge